name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch, e.g., master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Updated to use Node 18

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build  # Ensure this matches your project's build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Ensure this matches Vite's output directory. Default is `dist`, but check your vite.config.js
